# Generated by Django 4.1 on 2024-01-19 03:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total",
            field=models.CharField(default="1", max_length=50),
            preserve_default=False,
        ),
    ]
